### ISSUE TITLE
Add Skeleton Loading to the Projects Section

### ISSUE THREAD

**Issue by Atharv-110** [graphicmade/contribhub#10]
# Feature Request: To Add Skeleton Loading to Projects Card

## Description
Implementation of a Skeleton Loading  component to the Project cards on the Home Page so that it won't feel sticky till data renders.

## Dependencies:
- Add a skeleton component from shadcn/ui to the project. As I can see shadcn/ui is being used throughout the project.

@swve I would like to work on this issue. So please if possible assign this issue to me and add hacktoberfest label.

Thanks & Regards,
Atharv Vani

**Comment by swve** [comment]
Hello @Atharv-110, Nice Idea! Go ahead, here is some notes : 
- Can you please take inspiration from the skeletons on the project page (colors, components, etc.)

**Comment by Atharv-110** [comment]
Sure @swve I will keep in mind to make the styling consistent as it is in project.

**Comment by Keshav-1803** [comment]
If this issue is still open... Can you please assign this to me ??

**Comment by Atharv-110** [comment]
@swve please assign this issue to someone else, I haven't yet started it.

**Comment by souravseal99** [comment]
Hey @swve , can I take this one up?

**Comment by swve** [comment]
Hey @souravseal99, it's yours.
