### ISSUE TITLE
Organising the Search bar

### ISSUE THREAD

**Issue by citruswhale** [graphicmade/contribhub#12]
**Issue Description:** 
- The filter buttons in the search bar, such as "Groups", "Contributions", and others, need additional padding on the sides to improve their spacing and overall appearance. 
- The size constraint is bringing the "Hacktoberfest" button down a little. 

**Proposed Solution:** 
- Update the CSS for the filter buttons to add more horizontal padding, enhancing the spacing between text and button edges for a cleaner look. 
- Readjust the search bar size according to the device sizes 

![image](https://github.com/user-attachments/assets/7b4b05cc-2a5f-425f-bceb-04fa54a47707)

**Comment by swve** [comment]
Great Idea @citruswhale! i've already some tweaks for the mobile sizes, like in here where the round radius changes

<img width="784" alt="image" src="https://github.com/user-attachments/assets/239ab78b-dca2-4662-a1d3-3ff7bff4c3eb"><br>

Yeah I think it would be better if in the mobile versions the filters all go down or have their own separate centered div and the search bar would take the top of the Findbar, something like this minus the "groups" filter

<img width="579" alt="image" src="https://github.com/user-attachments/assets/7e655aae-5208-4ef9-9ed5-e0941f22d271">

**Comment by lonewolf9277** [comment]
Hey may I work on this?

**Comment by ansh-saini** [comment]
I'd like to work on this

**Comment by citruswhale** [comment]
Those are some great ideas! I'd also like to propose that we could have a
single line search bar, by extending the size a bit when it comes to full
screen laptop sizes. Could you pls assign this task to me?
