### ISSUE TITLE
Add Open Issues Counter based on Filter

### ISSUE THREAD

**Issue by rog404** [graphicmade/contribhub#13]
![image](https://github.com/user-attachments/assets/fc3912e9-5b80-4a31-a10b-05a5694194c6)

I'd like to propose adding a counter for open issues in the project, specifically reflecting the current filter settings. Here are some ideas for implementation:

**Display Options:**

- We could show the exact number of open issues.
- Alternatively, if the count exceeds 99, we could display "99+" for a cleaner look. (I'm not sure about it)

**Badge Style:**

- The counter could be styled as a badge for better visibility and aesthetics.
![image](https://github.com/user-attachments/assets/fa6c3893-c67c-4269-a2e8-9922ddc8172b)

**What do you think of this idea? I'm happy to work on it further if there's interest!**

**Comment by swve** [comment]
Cool idea @rog404 ! you can start working on it :)

**Comment by swve** [comment]
@rog404 Any status on this ?

**Comment by rog404** [comment]
Hi @swve 

To be honest, I haven't had enough time to finish the PR yet. I faced some difficulties with the Supabase setup (first time using it).

I will pay more attention to this issue today and tomorrow. Is that okay?

Sorry for the delay.

**Comment by swve** [comment]
Take your time @rog404, I just wanted to confirm that you're still on the issue 🫡
