### ISSUE TITLE
Share button

### ISSUE THREAD

**Issue by swve** [graphicmade/contribhub#14]
Ability to share a project to socials : 

- X, Facebook, HackerNews, Reddit etc 
- Position : next to stars

**Comment by iitzIrFan** [comment]
Can I work on this issue as I think , can work on it !

**Comment by swve** [comment]
Yes go ahead @iitzIrFan

**Comment by iitzIrFan** [comment]
Thank you for the opportunity but I’m unable to work on your project at this time.

**Comment by shanksxz** [comment]
@swve,  I'd love to take on this issue.

**Comment by shanksxz** [comment]
@swve Is there any seeding data for this project? Thanks!

**Comment by shanksxz** [comment]
@swve, for the share button, should we use the GitHub URL or the ContribHub project URL ([https://contribhub.com/project/ab5dc3a8-442d-4a4f-9417-282fe7766b49](https://contribhub.com/project/ab5dc3a8-442d-4a4f-9417-282fe7766b49)

**Comment by shanksxz** [comment]
demo:
Uploading 9bca0d26-f28a-4d95-a6cd-79e32e3b1da8_restream.mp4…

**Comment by swve** [comment]
@shanksxz 
- I think you can use the ContribHub project URL
- The share button should be on the project page only

**Comment by shanksxz** [comment]
Demo:
https://github.com/user-attachments/assets/32b65332-ff35-484e-bc79-729dfa0de625

**Comment by swve** [comment]
This is awesome @shanksxz, it does look and work as I would imagined it to be, really appreciate it
