### ISSUE TITLE
Dev Environment Docs

### ISSUE THREAD

**Issue by swve** [graphicmade/contribhub#15]
Complete the docs to add more details about how to seed the database and get a dev environment up and running quickly 
- File : CONTRIBUTING.md 
- Docs should be easy to follow and straightforward

**Comment by iitzIrFan** [comment]
Can I get this issue assigned to me so that I can work on this issue !

**Comment by swve** [comment]
@iitzIrFan are you sure you wan to work on this one alongside the other one ?

**Comment by iitzIrFan** [comment]
@swve I'm not familiar with Next.js but I can surely contribute by working on the project documentation here.

**Comment by swve** [comment]
@iitzIrFan are you familiar with Supabase ?

**Comment by iitzIrFan** [comment]
@swve Have worked a little in my previous project and know that it's a FireBase alternative !

**Comment by swve** [comment]
Great, the docs is missing a step : how to import the schema to a local supabase database from the seed.sql, you only need to copy the sql text and insert it in the supabase dashboard interface, SQL page. 

And if you see any additional things to be added don't hestitate

**Comment by shanksxz** [comment]
@iitzIrFan what's the status?

**Comment by iitzIrFan** [comment]
@shanksxz Apologies for the delay. I’ll update the documentation soon and provide an update once it's done. Let me know if there’s anything specific you’d like included.

**Comment by iitzIrFan** [comment]
Need review on this :- 

https://github.com/user-attachments/assets/2503394f-41bc-46ba-804e-d5a87176c915

**Comment by swve** [comment]
@iitzIrFan LGTM from your video, you can make a PR 👍

**Comment by iitzIrFan** [comment]
@swve I had made a PR req do merge it into your main branch !

**Comment by iitzIrFan** [comment]
@swve I had pushed the necessary changes in my pr req so do merge it into your main branch !

**Comment by iitzIrFan** [comment]
@swve I had pushed the necessary changes in my pr req so do merge it into your main branch !
