### ISSUE TITLE
Feature : Add Scroll To Top Button to the Website.

### ISSUE THREAD

**Issue by rajgharat07** [graphicmade/contribhub#16]
- The "Scroll to Top" button is a simple, yet highly useful UI element that allows users to quickly navigate back to the top of the webpage after they have scrolled down. This feature enhances user experience, particularly on long webpages, by providing a quick and easy way to return to the beginning of the page without manually scrolling all the way up.

- Adding this feature will improve navigation convenience, resulting in a more polished and user-friendly browsing experience.

- # Proposed Solution

  - The solution is to implement a "Scroll to Top" button that appears when users scroll down a certain distance (e.g., after scrolling 200px from the top). When clicked, this button smoothly scrolls the page back to the top.
  
  - Steps to Implement :
  
  - Create the Button :
  
    - Add a small button (e.g., an up-arrow icon) fixed at the bottom-right corner of the viewport. Initially, this button will be hidden.
  
  - Show the Button on Scroll :
  
    - Using JavaScript or a front-end framework (like React or Vue), add an event listener that tracks the user's scroll position. Once the user has scrolled down beyond a certain threshold (e.g., 200px), the button becomes visible.
  
  - Smooth Scroll Behavior :
  
    - When the user clicks the button, implement smooth scrolling behavior that takes the user back to the top of the page.
  
  - Hide the Button at the Top :
  
    - When the user is near or at the top of the page, the button should hide again.

**Comment by sankettank66** [comment]
@swve I want to contribute. Can you assign this issue to me?

**Comment by Keshav-1803** [comment]
If this issue is not being worked on and is open then i would like to work on this !!
