### ISSUE TITLE
Enhance Interface Interaction with Hover Color Change

### ISSUE THREAD

**Issue by PragyaTripathi990** [graphicmade/contribhub#18]
To improve the user interface and provide clearer feedback, we propose adding a color change effect to the interface elements on hover. This enhancement will help users identify which element they are interacting with, making the interface more intuitive and visually appealing.
Current State: Elements remain static without any visual feedback when hovered over.
Proposed Change: On mouse hover, the background color of the element should change to a lighter or more vibrant color. This can be implemented using CSS, utilizing the :hover pseudo-class.
Color Suggestions: Consider using a subtle shade that contrasts with the current element color, ensuring it remains accessible and visually pleasing.
<img width="1301" alt="Screenshot 2024-10-13 at 7 21 42 AM" src="https://github.com/user-attachments/assets/779604e1-fdfb-45da-b942-5fb9f9ba4efc">

**Comment by swve** [comment]
Hey @PragyaTripathi990, can you show me some experimental hovers you did with this ?

**Comment by sankettank66** [comment]
@swve can you assign this issue to me?

**Comment by Love-Deep-Singh** [comment]
Hey @swve  can i work on this here is what i think looks good
![Screenshot (562)](https://github.com/user-attachments/assets/030ea09b-3353-4570-bc04-93abe152a762)

![Screenshot (563)](https://github.com/user-attachments/assets/36031f39-840c-44f7-8433-eac00e324150)
