### ISSUE TITLE
Feature : Edit a project from Contribhub

### ISSUE THREAD

**Issue by swve** [graphicmade/contribhub#25]
Hi Everyone,
Thanks for your interest in ContribHub

### Implementation
- Ability to edit individual projects from https://contribhub.com/dashboard/projects 
- A new page `https://contribhub.com/dashboard/projects/projectuuid/edit` should be added
- Design and page should be inspired from `https://contribhub.com/dashboard/projects/new`
- Edit function should be used server side and using the serviceRole supabase client 

### Difficulty Level 
- Experience with Supabase and SQL 
- Experience with Next.js 

Please make sure you're able to properly work this issue before asking to assigned.

Thanks 🤗

**Comment by Keshav-1803** [comment]
I would like to work on this issue !!

**Comment by swve** [comment]
Hello @Keshav-1803, of course. I've now assigned the issue to you.

**Comment by swve** [comment]
It looks like @ntheanh201 has taken the issue now, i'll be reviewing this shortly. 

@Keshav-1803 Hoping that you've not started this one yet, I invite you to take on another one or to help review https://github.com/graphicmade/contribhub/pull/28 

Thanks to you two
