### ISSUE TITLE
SEO : Add dynamic metadata to a project page

### ISSUE THREAD

**Issue by swve** [graphicmade/contribhub#26]
Hi Everyone,
Thanks for your interest in ContribHub

### Implementation
- Create a new Server Component page 
- Use it as a **page.tsx** and migrate the current one to a **client.tsx** Client component 
- Use the Client component in the **page.tsx** 
- Generate metadata about a project in the **page.tsx** 
- Take inspiration from here : https://github.com/learnhouse/learnhouse/blob/dev/apps/web/app/orgs/%5Borgslug%5D/(withmenu)/page.tsx#L29 
- Use `getProjectByUuid(params.projectuuid);` to get what you need to use for the metadata

### Difficulty Level 
- Experience with Supabase and SQL 
- Experience with SEO
- Experience with Next.js App Router

Please make sure you're able to properly work this issue before asking to assigned.

Thanks 🤗

**Comment by Keshav-1803** [comment]
I wanna try working on this issue ...

**Comment by Keshav-1803** [comment]
But someone has already created a PR for #25. Please Check. So, If this issue is still available I would like to give it a try.

**Comment by swve** [comment]
Hello @ntheanh201, this is awesome!

Not only you did flawlessly add dynamic metadata to the page but you also had the brilliant idea of fetching project data server-side and passing it to the client component, resulting in increased performance and potentially fixing hundreds of "Soft 404" issues I had with Google.

I really appreciate your work, it is of great quality!

Thanks
