### ISSUE TITLE
404 Error on Profile Page (https://contribhub.com/profile)

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [graphicmade/contribhub#34]
Issue: Getting a 404 Page on clicking on the Profile icon 

![Screenshot from 2024-10-18 17-45-26](https://github.com/user-attachments/assets/51a009e8-aa6e-4b9a-a2b0-fd7114637034)

Solution: 

1. We can redirect to the GitHub account of the user 
2. We can also create a dedicated profile page for each user.

**Comment by Muhammad-Owais-Warsi** [comment]
I would love to solve the issue.

**Comment by arpitkuriyal** [comment]
can you assign me the issue . I can do it

**Comment by Muhammad-Owais-Warsi** [comment]
> I would love to solve the issue.

@arpitkuriyal

**Comment by swve** [comment]
Hello @Muhammad-Owais-Warsi, is there any link that refer to this page ?

**Comment by Muhammad-Owais-Warsi** [comment]
Hi @swve, on this [page](https://contribhub.com/dashboard/projects/new), or simply when we create a project, we can see our profile at the bottom right. When you click there, it redirects us to https://contribhub.com/profile, which results in a 404 page. Thanks!

**Comment by swve** [comment]
@Muhammad-Owais-Warsi, could you please remove the profile link from the bottom right? It's not a feature we have planned yet. Thank you!

**Comment by Muhammad-Owais-Warsi** [comment]
Sure 👍

**Comment by Muhammad-Owais-Warsi** [comment]
> ould you please remove the pro

Just to make sure, should I remove this whole block or jut change the link form `/profie` to `/`
```javascript
          <TooltipWrapper content="Profile">
            <Link href="/profile" className="w-8 h-8 bg-white rounded-full shadow-md flex items-center justify-center">
              <img
                src={session.user.user_metadata.avatar_url || '/default-avatar.png'}
                alt="User Avatar"
                width={24}
                height={24}
                className="rounded-full nice-shadow "
              />
            </Link>
          </TooltipWrapper>
````

**Comment by Muhammad-Owais-Warsi** [comment]
> Thanks @Muhammad-Owais-Warsi, no just removing the link will do. I guess you can turn the `<Link>` into a `div` and remove the `href` attribute

Sure, thanks

**Comment by Muhammad-Owais-Warsi** [comment]
> Thanks @Muhammad-Owais-Warsi, no just removing the link will do. I guess you can turn the `<Link>` into a `div` and remove the `href` attribute

#36
