### ISSUE TITLE
Add Dark/Light Theme Toggle with Persistent User Preference

### ISSUE THREAD

**Issue by VanshChitransh** [graphicmade/contribhub#6]
# Feature Request: Dark/Light Theme Toggle

## Description
Implement a feature that allows users to toggle between dark and light themes on the **contrihub** platform. The user's theme preference should be stored and persist across sessions.

## Requirements
- Add a toggle button for switching between dark and light themes.
- Store the user's theme preference using local storage or cookies.
- Ensure the theme persists even after the page is refreshed or when the user revisits the site.
- Default to the user's system-wide theme preference if no previous selection is stored.

## Additional Information
- Use Tailwind CSS or the current CSS framework for theme-related styles.
- Ensure compatibility across different browsers and devices.
- Follow accessibility guidelines for contrast and readability in both themes.

### Related Files/Modules
- Navigation bar component
- CSS/Theme files

### Dependencies
- Tailwind CSS (or applicable CSS framework)
- Local storage or equivalent to save user preferences

### Priority
Medium

### Difficulty
Moderate

## Relevant Links
N/A

**Comment by VanshChitransh** [comment]
@swve I would love to work on this issue.

**Comment by swve** [comment]
@VanshChitransh Absolutely, Dark Mode is such a cool thing to have on a website, here is some notes : 
- I would prefer if we store the data in localStorage.
- The overall design should follow the app design style, I'll be happy to support on you on the design side to make it as adapted as possible to the current light mode. 
- I'm okay with the rest of the requirements.

Thanks for the complete issue description, I really appreciate this and your contribution!

**Comment by swve** [comment]
Is this part of #Hacktoberfest ? so that I can add the labels.

**Comment by VanshChitransh** [comment]
@swve  Thank you for assigning me the issue. I will keep all of your points in mind, and it would be helpful if you could add the Hacktoberfest label to it.

**Comment by Saiharitha3** [comment]
Hi @swve 
i want to work on this issue, is the issue still open can i make PR?

**Comment by shanksxz** [comment]
@VanshChitransh status?

**Comment by VanshChitransh** [comment]
@swve Please unassign me from this issue. Thanku

**Comment by shanksxz** [comment]
> @swve Please unassign me from this issue. Thanku

you can unassign yourself

**Comment by Saiharitha3** [comment]
@swve Please assign this issue to me

**Comment by swve** [comment]
I'm closing this issue, not the priority for now.
