### ISSUE TITLE
Add Feature to Edit Username in User Profile Settings

### ISSUE THREAD

**Issue by VanshChitransh** [graphicmade/contribhub#7]
# Feature Request: Edit Username Functionality

## Description
Implement a feature that allows users to edit their username on the **contrihub** platform. This will enable users to update their display name if needed, improving the overall user experience.

## Requirements
- Add an "Edit Username" option in the user profile settings.
- Provide an input field where users can update their username.
- Ensure validation for the username, such as minimum/maximum length, allowed characters, and uniqueness.
- Provide feedback for successful username updates or errors (e.g., username already taken).
- Save the updated username and ensure it reflects across the platform (profile, posts, comments, etc.).

## Screenshot
_Add a relevant screenshot or wireframe here showing where the "Edit Username" option will appear in the UI._

![Screenshot from 2024-10-10 22-13-21](https://github.com/user-attachments/assets/cd117ed8-b77a-46f6-8967-4d9df30ad123)

## Additional Information
- Consider adding debounce functionality to check the availability of the new username in real-time.
- Follow proper user experience practices by providing clear instructions and feedback.

### Related Files/Modules
- User profile component
- User data management logic (backend)

### Dependencies
- Backend service for updating and validating usernames.
- User authentication to ensure only authorized changes are made.

### Priority
High

### Difficulty
Moderate

## Relevant Links
N/A

**Comment by VanshChitransh** [comment]
@swve I would love to work on this issue.

**Comment by swve** [comment]
Hi @VanshChitransh, great idea! This will be handy when we'll add community based features to the app 🤗 
Is this part of #Hacktoberfest ? so that I can add the labels.

**Comment by VanshChitransh** [comment]
@swve  Thank you for your appreciation. Yes, please add the Hacktoberfest label to it. I will do my best to deliver on this issue.
